<html>
<head>
    <meta name="viewport" content="width=1980, initial-scale=1"/>
    <title>Welcome!</title>
</head>
<body>
<h1>This is a test Contract</h1>
<p>Terms and Conditions:
    Read carefully!
</p>

<p>
<div id="first-signer">
    <div>
        <span>First Signer:</span>
        <span id="sign-1"></span>
    </div>
</div>

<div id="second-signer">
    <div>
        <span>Second Signer:</span>
        <span id="sign-2"></span>
    </div>
</div>
</p>

</body>
</html>